name: bothnia_server
description: En webbserver för att hantera Bothniabladets bildsamlingar.
version: 0.0.1
author: Christian Mårtensson <chrism.marten@gmail.com>

environment:
  sdk: ">=2.7.0"  


dependencies:
  aqueduct: ^3.3.0+1
  mime: ^0.9.6+3
  http_server: ^0.9.8+3



dev_dependencies:
  test: ^1.0.1
  aqueduct_test: ^1.0.1
